// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbmqwevifguswnqktnnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhibXF3ZXZpZmd1c3ducWt0bm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MTYzMzYsImV4cCI6MjA1MTE5MjMzNn0.X3vSS_qKndg0P3ZhyIIcSVYcLmD-gLMEzQVj4k0qTdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);