// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { useSupabaseClient as useSupabaseClientOriginal } from '@supabase/auth-helpers-react';
import { Database } from './types';

export const supabase = createClient<Database>(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY
);

export const useSupabaseClient = useSupabaseClientOriginal;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";